CREATE TABLE spotify_2023 (
    track_name TEXT,
    artist_name TEXT,
    artist_count INTEGER,
    released_year INTEGER,
    released_month INTEGER,
    released_day INTEGER,
    in_spotify_playlists INTEGER,
    in_spotify_charts INTEGER,
    streams BIGINT,
    in_apple_playlists INTEGER,
    in_apple_charts INTEGER,
    in_deezer_playlists TEXT,  
    in_deezer_charts INTEGER,
    in_shazam_charts TEXT,  
    bpm INTEGER,
    key TEXT,
    mode TEXT,
    danceability_percent INTEGER,
    valence_percent INTEGER,
    energy_percent INTEGER,
    acousticness_percent INTEGER,
    instrumentalness_percent INTEGER,
    liveness_percent INTEGER,
    speechiness_percent INTEGER
);
